version: "3"

services:
 
  database:
    image: 'postgres:13.1-alpine'
    container_name: bixb-database
    restart: always
    tty: true
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=bixb
      - POSTGRES_PASSWORD=bixb
      - POSTGRES_DB=bixb
    volumes: 
      - ./postgresql-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks: 
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    networks: 
      - net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      #KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: LISTENER_PUBLIC://kafka:29092,LISTENER_INTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_PUBLIC://kafka:29092,LISTENER_INTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_PUBLIC:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_PUBLIC

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - net
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  crud-api:
    image: 'crud-api:latest'
    build:
      context: ./crud-api
    tty: true      
    container_name: crud-api
    depends_on:
      - kafka
      - database
    stdin_open: true
    networks:
      - net
    ports: 
      - "8080:8080"

  producer-api:
    image: 'producer-api:latest'
    build:
      context: ./producer-api
    tty: true      
    container_name: producer-api
    stdin_open: true
    depends_on:
      - crud-api
    networks:
      - net
    ports: 
      - "8081:8080"

networks:
  net:
    driver: bridge     